package com.layoutxml.sabs.model;

import java.util.ArrayList;
import java.util.List;

public class AdhellPermissionInfo {
    public final String name;
    public final String label;

    public AdhellPermissionInfo(String name, String label) {
        this.name = name;
        this.label = label;

    }

    public static List<AdhellPermissionInfo> loadPermissions() {

        List<AdhellPermissionInfo> lis = new ArrayList<>();
        lis.add(new AdhellPermissionInfo("android.permission.INTERNET", "Internet"));
        lis.add(new AdhellPermissionInfo("android.permission.CAMERA", "Access the camera device"));
        lis.add(new AdhellPermissionInfo("android.permission.RECORD_AUDIO", "Record audio"));
        lis.add(new AdhellPermissionInfo("android.permission.WAKE_LOCK", "Allows using PowerManager WakeLocks to keep processor from sleeping or screen from dimming"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_SMS", "Send SMS messages"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_SMS", "Receive SMS messages"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_MMS", "Monitor incoming MMS messages"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_WIFI_STATE", "Access information about Wi-Fi networks"));
        lis.add(new AdhellPermissionInfo("android.permission.BATTERY_STATS", "Collect battery statistics"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH", "Connect to paired bluetooth devices"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_ADMIN", "Discover and pair bluetooth devices"));
        lis.add(new AdhellPermissionInfo("android.permission.USE_FINGERPRINT", "Use fingerprint hardware"));
        lis.add(new AdhellPermissionInfo("android.permission.VIBRATE", "Access to the vibrator"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NETWORK_STATE", "Access information about networks"));

        // dangerous
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_COARSE_LOCATION", "Access approximate location"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_FINE_LOCATION", "Access precise location"));
        lis.add(new AdhellPermissionInfo("android.permission.ANSWER_PHONE_CALLS", "Answer an incoming phone call"));
        lis.add(new AdhellPermissionInfo("android.permission.CALL_PHONE", "Initiate a phone call without going through the Dialer user interface for the user to confirm the call"));
        lis.add(new AdhellPermissionInfo("android.permission.BODY_SENSORS", "Access data from sensors that the user uses to measure what is happening inside his/her body, such as heart rate"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_ACCOUNTS", "Allows access to the list of accounts in the Accounts Service"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_ACCOUNTS_PRIVILEGED", "Allows access to the list of accounts in the Accounts Service (Since 6.0)"));
        lis.add(new AdhellPermissionInfo("android.permission.PROCESS_OUTGOING_CALLS", "See the number being dialed during an outgoing call with the option to redirect the call to a different number or abort the call altogether"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CALENDAR", "Read the user's calendar data"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CALENDAR", "Write the user's calendar data"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CALL_LOG", "Read the user's call log"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CALL_LOG", "Write (but not read) the user's call log data"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_CONTACTS", "Read the user's contacts data"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_CONTACTS", "Write the user's contacts data"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_EXTERNAL_STORAGE", "Read from external storage"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_EXTERNAL_STORAGE", "Write to external storage"));
        lis.add(new AdhellPermissionInfo("android.permission.USE_SIP", "Use SIP service"));

        // normal
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_LOCATION_EXTRA_COMMANDS", "Access extra location provider commands"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PACKAGE_SIZE", "Find out the space used by any package"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PHONE_STATE", "Allows read access to phone state (phone number, current network info)"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_NETWORK_STATE", "Change network connectivity state"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIFI_MULTICAST_STATE", "Enter Wi-Fi Multicast mode"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIFI_STATE", "Change Wi-Fi connectivity state"));
        lis.add(new AdhellPermissionInfo("android.permission.DISABLE_KEYGUARD", "Disable the keyguard if it is not secure"));
        lis.add(new AdhellPermissionInfo("android.permission.EXPAND_STATUS_BAR", "Expand or collapse the status bar"));
        lis.add(new AdhellPermissionInfo("com.android.launcher.permission.INSTALL_SHORTCUT", "Install a shortcut in Launcher"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_AUDIO_SETTINGS", "Modify global audio settings"));
        lis.add(new AdhellPermissionInfo("android.permission.NFC", "Perform I/O operations over NFC"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SMS", "Read SMS messages"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SYNC_SETTINGS", "Read the sync settings"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SYNC_STATS", "Read the sync stats"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SYNC_SETTINGS", "Write the sync settings"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_BOOT_COMPLETED", "Receive Boot Completed"));
        lis.add(new AdhellPermissionInfo("com.android.alarm.permission.SET_ALARM", "Set an alarm for the user"));

        //untested
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_ALL_DOWNLOADS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_BLUETOOTH_SHARE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_CACHE_FILESYSTEM", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_CHECKIN_PROPERTIES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_DOWNLOAD_MANAGER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_DOWNLOAD_MANAGER_ADVANCED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_DRM_CERTIFICATES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_EPHEMERAL_APPS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_FM_RADIO", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_INPUT_FLINGER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_KEYGUARD_SECURE_STORAGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_MOCK_LOCATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_MTP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NETWORK_CONDITIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NOTIFICATIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_NOTIFICATION_POLICY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_PDB_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_SURFACE_FLINGER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_VOICE_INTERACTION_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_VR_MANAGER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCESS_WIMAX_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ACCOUNT_MANAGER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_ACCESS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_CREATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_DESTROY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_MOUNT_UNMOUNT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.ASEC_RENAME", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.AUTHENTICATE_ACCOUNTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BACKUP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_ACCESSIBILITY_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_APPWIDGET", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CARRIER_MESSAGING_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CARRIER_SERVICES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CHOOSER_TARGET_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CONDITION_PROVIDER_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_CONNECTION_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DEVICE_ADMIN", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DIRECTORY_SEARCH", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_DREAM_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INCALL_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INPUT_METHOD", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_INTENT_FILTER_VERIFIER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_JOB_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_KEYGUARD_APPWIDGET", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_MIDI_DEVICE_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NFC_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NOTIFICATION_LISTENER_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_NOTIFICATION_RANKER_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PACKAGE_VERIFIER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PRINT_RECOMMENDATION_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PRINT_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_PRINT_SPOOLER_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_QUICK_SETTINGS_TILE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_REMOTEVIEWS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_REMOTE_DISPLAY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_ROUTE_PROVIDER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_RUNTIME_PERMISSION_PRESENTER_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_SCREENING_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TELECOM_CONNECTION_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TEXT_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TRUST_AGENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TV_INPUT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_TV_REMOTE_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VOICE_INTERACTION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VPN_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_VR_LISTENER_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BIND_WALLPAPER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_MAP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_PRIVILEGED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BLUETOOTH_STACK", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BRICK", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_CALLLOG_INFO", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_NETWORK_PRIVILEGED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_PACKAGE_REMOVED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_PHONE_ACCOUNT_REGISTRATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_SMS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_STICKY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.BROADCAST_WAP_PUSH", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CACHE_CONTENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CALL_PRIVILEGED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CAMERA_DISABLE_TRANSMIT_LED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CAMERA_SEND_SYSTEM_EVENTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_AUDIO_HOTWORD", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_AUDIO_OUTPUT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_SECURE_VIDEO_OUTPUT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_TV_INPUT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CAPTURE_VIDEO_OUTPUT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CARRIER_FILTER_SMS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_APP_IDLE_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_BACKGROUND_DATA_SETTING", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_COMPONENT_ENABLED_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_CONFIGURATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CHANGE_WIMAX_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CLEAR_APP_CACHE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CLEAR_APP_GRANTED_URI_PERMISSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CLEAR_APP_USER_DATA", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONFIGURE_DISPLAY_COLOR_TRANSFORM", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONFIGURE_WIFI_DISPLAY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONFIRM_FULL_BACKUP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONNECTIVITY_INTERNAL", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_INCALL_EXPERIENCE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_KEYGUARD", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_LOCATION_UPDATES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_VPN", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CONTROL_WIFI_DISPLAY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.COPY_PROTECTED_DATA", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CREATE_USERS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.CRYPT_KEEPER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DELETE_CACHE_FILES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DELETE_PACKAGES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DEVICE_POWER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DIAGNOSTIC", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DISPATCH_NFC_MESSAGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DISPATCH_PROVISIONING_MESSAGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DOWNLOAD_CACHE_NON_PURGEABLE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DUMP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.DVB_DEVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.FACTORY_TEST", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.FILTER_EVENTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.FLASHLIGHT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.FORCE_BACK", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.FORCE_STOP_PACKAGES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.FRAME_STATS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.FREEZE_SCREEN", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_APP_GRANTED_URI_PERMISSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_APP_OPS_STATS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_DETAILED_TASKS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_INTENT_SENDER_INTENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PACKAGE_IMPORTANCE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PASSWORD", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_PROCESS_STATE_AND_OOM_SCORE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_TASKS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GET_TOP_ACTIVITY_INFO", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GLOBAL_SEARCH", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GLOBAL_SEARCH_CONTROL", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.GRANT_RUNTIME_PERMISSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.HARDWARE_TEST", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.HDMI_CEC", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INJECT_EVENTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_LOCATION_PROVIDER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INSTALL_PACKAGES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INTENT_FILTER_VERIFICATION_AGENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INTERACT_ACROSS_USERS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INTERACT_ACROSS_USERS_FULL", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INTERNAL_SYSTEM_WINDOW", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.INVOKE_CARRIER_SETUP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.KILL_BACKGROUND_PROCESSES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.KILL_UID", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.LAUNCH_TRUST_AGENT_SETTINGS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.LOCAL_MAC_ADDRESS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.LOCATION_HARDWARE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.LOOP_RADIO", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_ACCOUNTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_ACTIVITY_STACKS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_APP_OPS_RESTRICTIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_APP_TOKENS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_CA_CERTIFICATES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_DEVICE_ADMINS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_DOCUMENTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_FINGERPRINT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_MEDIA_PROJECTION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_NETWORK_POLICY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_NOTIFICATIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_PROFILE_AND_DEVICE_OWNERS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_SOUND_TRIGGER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_USB", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_USERS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MANAGE_VOICE_KEYPHRASES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MASTER_CLEAR", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MEDIA_CONTENT_CONTROL", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_AUDIO_ROUTING", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_CELL_BROADCASTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_DAY_NIGHT_MODE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_NETWORK_ACCOUNTING", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_PARENTAL_CONTROLS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MODIFY_PHONE_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MOUNT_FORMAT_FILESYSTEMS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MOUNT_UNMOUNT_FILESYSTEMS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.MOVE_PACKAGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.NET_ADMIN", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.NET_TUNNELING", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.NFC_HANDOVER_STATUS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.NOTIFY_PENDING_SYSTEM_UPDATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.OEM_UNLOCK_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.OVERRIDE_WIFI_CONFIG", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PACKAGE_USAGE_STATS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PACKAGE_VERIFICATION_AGENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PACKET_KEEPALIVE_OFFLOAD", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PEERS_MAC_ADDRESS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PERFORM_CDMA_PROVISIONING", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PERFORM_SIM_ACTIVATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PERSISTENT_ACTIVITY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PROCESS_CALLLOG_INFO", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PROCESS_PHONE_ACCOUNT_REGISTRATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.PROVIDE_TRUST_AGENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.QUERY_DO_NOT_ASK_CREDENTIALS_ON_BOOT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_BLOCKED_NUMBERS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_DREAM_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_FRAME_BUFFER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_INPUT_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_INSTALL_SESSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_LOGS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_NETWORK_USAGE_HISTORY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_OEM_UNLOCK_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PRECISE_PHONE_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PRIVILEGED_PHONE_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_PROFILE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SEARCH_INDEXABLES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_SOCIAL_STREAM", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_USER_DICTIONARY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.READ_WIFI_CREDENTIAL", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REAL_GET_TASKS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REBOOT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_BLUETOOTH_MAP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_DATA_ACTIVITY_CHANGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_EMERGENCY_BROADCAST", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_MEDIA_RESOURCE_USAGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_STK_COMMANDS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RECEIVE_WIFI_CREDENTIAL_CHANGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RECOVERY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_CALL_PROVIDER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_CONNECTION_MANAGER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_SIM_SUBSCRIPTION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REGISTER_WINDOW_MANAGER_LISTENERS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REMOTE_AUDIO_PLAYBACK", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REMOVE_DRM_CERTIFICATES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REMOVE_TASKS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REORDER_TASKS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REQUEST_INSTALL_PACKAGES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RESET_FINGERPRINT_LOCKOUT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RESET_SHORTCUT_MANAGER_THROTTLING", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RESTART_PACKAGES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RETRIEVE_WINDOW_CONTENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.RETRIEVE_WINDOW_TOKEN", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.REVOKE_RUNTIME_PERMISSIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SCORE_NETWORKS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_CALL_LOG_CHANGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_DOWNLOAD_COMPLETED_INTENTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_RESPOND_VIA_MESSAGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SEND_SMS_NO_CONFIRMATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SERIAL_PORT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ACTIVITY_WATCHER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ALWAYS_FINISH", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ANIMATION_SCALE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_DEBUG_APP", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_INPUT_CALIBRATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_KEYBOARD_LAYOUT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_ORIENTATION", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_POINTER_SPEED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_PREFERRED_APPLICATIONS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_PROCESS_LIMIT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_SCREEN_COMPATIBILITY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_TIME", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_TIME_ZONE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER_COMPONENT", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SET_WALLPAPER_HINTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SHUTDOWN", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SIGNAL_PERSISTENT_PROCESSES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.START_ANY_ACTIVITY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.START_PRINT_SERVICE_CONFIG_ACTIVITY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.START_TASKS_FROM_RECENTS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.STATUS_BAR", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.STATUS_BAR_SERVICE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.STOP_APP_SWITCHES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.STORAGE_INTERNAL", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SUBSCRIBED_FEEDS_READ", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SUBSCRIBED_FEEDS_WRITE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.SYSTEM_ALERT_WINDOW", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.TABLET_MODE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.TEMPORARY_ENABLE_ACCESSIBILITY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.TETHER_PRIVILEGED", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.TRANSMIT_IR", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.TRUST_LISTENER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.TV_INPUT_HARDWARE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.TV_VIRTUAL_REMOTE_CONTROLLER", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_APP_OPS_STATS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_CONFIG", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_DEVICE_STATS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_LOCK", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.UPDATE_LOCK_TASK_PACKAGES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.USER_ACTIVITY", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.USE_CREDENTIALS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_APN_SETTINGS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_BLOCKED_NUMBERS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_DREAM_STATE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_GSERVICES", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_MEDIA_STORAGE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_PROFILE", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SECURE_SETTINGS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SETTINGS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SMS", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_SOCIAL_STREAM", "Undocumented permission"));
        lis.add(new AdhellPermissionInfo("android.permission.WRITE_USER_DICTIONARY", "Undocumented permission"));




        return lis;
    }
}
